import puppeteer from 'puppeteer-core'
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
const b = await puppeteer.launch({ executablePath: CHROME, headless:'new', args:['--no-sandbox'] })
const p = await b.newPage()
const logs=[]; p.on('console',m=>logs.push(m.text()))
await p.goto('http://localhost:5194/', { waitUntil:'networkidle0' })
await new Promise(r=>setTimeout(r,800))
await p.evaluate(()=>{try{localStorage.removeItem('quill.tester')}catch{}})
await p.evaluate(()=>{const e=[...document.querySelectorAll('button,a')].find(x=>/continue as guest/i.test(x.textContent)); if(e)e.click()})
await new Promise(r=>setTimeout(r,700))
await p.evaluate(()=>{const e=[...document.querySelectorAll('button,a')].find(x=>/skip for now|not today/i.test(x.textContent)); if(e)e.click()})
await new Promise(r=>setTimeout(r,600))
await p.evaluate(()=>{const e=[...document.querySelectorAll('header nav button')].find(x=>/my quill/i.test(x.textContent)); if(e)e.click()})
await new Promise(r=>setTimeout(r,1400))
await p.evaluate(()=>{const e=[...document.querySelectorAll('button')].find(x=>/have a tester code/i.test(x.textContent)); if(e){e.scrollIntoView({block:'center'});e.click()}})
await new Promise(r=>setTimeout(r,500))
await p.focus('input[type="text"]')
await p.keyboard.type('testerBeta')
await p.evaluate(()=>{const e=[...document.querySelectorAll('button')].find(x=>/unlock/i.test(x.textContent)); if(e)e.click()})
await new Promise(r=>setTimeout(r,5000))
console.log('RESULT:', JSON.stringify(await p.evaluate(()=>document.body.innerText.match(/Beta tester access is on|didn.t work/i)?.[0])))
console.log('tester flag:', await p.evaluate(()=>localStorage.getItem('quill.tester')))
await b.close()
